# This is a basic workflow to help you get started with Actions

name: versions:2016.0

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string 1:00  weekly,Wednesday,1:00 #m h d/m m d/w 
    - cron:  '33 2 * * 3'

jobs:
  versions:
    runs-on: ubuntu-20.04
    container:
      image: credocker/crepostgres:2016.0
      # https://github.com/actions/checkout/issues/1014
      # https://github.com/actions/checkout/issues/956
      options: --user root
    steps:
      - name: find node
        run: (ls -l /usr/local/bin)
      #- name: node16 vs node20
      #  run: (cd $RUNNER_HOME/actions-runner/externals; mv node20 node20.bak; ln -s node16 node20) 

      - uses: actions/checkout@v3
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
      - name: cat version.txt
        run: (cat /cre/versions.txt) 
      - name: cp version.txt
#        run: (cp /cre/versions.txt cre/versions/versions_2016.txt) 
        run: (cut -f2,3 /cre/versions.txt > cre/versions/versions_2016.txt)
      - name: Submit changes       
        uses: EndBug/add-and-commit@v9
        with:
#          pull: '--rebase --autostash ...'
          add: 'cre/versions/versions_2016.txt'
          tag_push: '--force'
